language: objective-c
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2
env:
  global:
  - PROJECT=NVActivityIndicatorView.xcodeproj
  - SCHEME=NVActivityIndicatorView
script:
  - set -o pipefail
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.0" clean test | xcpretty -c
